[platformio]
default_envs = m5stack_tab5

[env:m5stack_tab5]
; M5Stack Tab5 専用ボード定義 (ESP32-P4 + ESP32-C6 SDIO Wi-Fi)
platform = https://github.com/pioarduino/platform-espressif32.git
board = m5stack-tab5-p4
framework = arduino

board_build.f_cpu = 360000000L
board_build.flash_mode = dio
board_build.partitions = partitions_16mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -D CONFIG_MBEDTLS_DYNAMIC_BUFFER=1
    -D CONFIG_MBEDTLS_DYNAMIC_TX_BUFFER=1
    -D CONFIG_MBEDTLS_DYNAMIC_RX_BUFFER=1
    -D CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LV_CONF_INCLUDE_SIMPLE=1
    -I include
    -I src

lib_deps =
    m5stack/M5Unified @ ^0.2.1
    m5stack/M5GFX @ ^0.2.0
    m5stack/M5Module-LLM @ ^1.7.0
    lvgl/lvgl @ ^8.4.0
    bblanchon/ArduinoJson @ ^7.0.4
