[platformio]
default_envs = m5stack_tab5

[env:m5stack_tab5]
platform = espressif32 @ ^6.9.0
board = esp32-p4-function-ev-board
framework = arduino
board_build.mcu = esp32p4
board_build.f_cpu = 400000000L
board_build.flash_mode = dio

; PSRAM & Flash Settings for ESP32-P4
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -D LV_CONF_INCLUDE_SIMPLE=1
    -I include
    -I src

lib_deps =
    m5stack/M5Unified @ ^0.2.1
    m5stack/M5GFX @ ^0.2.0
    m5stack/M5Module-LLM @ ^1.7.0
    lvgl/lvgl @ ^8.4.0
    bblanchon/ArduinoJson @ ^7.0.4
    leethomason/tinyxml2 @ ^10.0.0
